# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  
  download:
    cmd: bash src/1_rsyncPDB.sh 
    deps:
      - https://files.wwpdb.org/pub/pdb/software/rsyncPDB.sh
    outs:
      - download

  process:
    cmd: Rscript src/2_process.R
    deps: 
      - download
    outs:
      - brick